## Упражнения по библиотеке Numpy

In [1]:
import numpy as np


**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [2]:
M = np.random.randint(0, 10, size=10)
print("Исходный массив:", M)
M[(M > 3) & (M < 8)] *= -1
print("Изменённый массив:", M)

Исходный массив: [9 0 3 6 8 6 9 8 8 3]
Изменённый массив: [ 9  0  3 -6  8 -6  9  8  8  3]


**2.** Заменить максимальный элемент случайного массива на 0

In [3]:
M[np.argmax(M)] = 0
print("Массив после замены максимального элемента на 0:", M)

Массив после замены максимального элемента на 0: [ 0  0  3 -6  8 -6  9  8  8  3]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [4]:
arr = np.array([
    [2, 4, 6],
    [1, 3, 5]
])
arr1 = np.array([
    [10, 11],
    [12, 13]
])
a, b = np.meshgrid(arr.ravel(), arr1.ravel())
dec_m = np.stack([a.ravel(), b.ravel()], axis=1)
print(dec_m)

[[ 2 10]
 [ 4 10]
 [ 6 10]
 [ 1 10]
 [ 3 10]
 [ 5 10]
 [ 2 11]
 [ 4 11]
 [ 6 11]
 [ 1 11]
 [ 3 11]
 [ 5 11]
 [ 2 12]
 [ 4 12]
 [ 6 12]
 [ 1 12]
 [ 3 12]
 [ 5 12]
 [ 2 13]
 [ 4 13]
 [ 6 13]
 [ 1 13]
 [ 3 13]
 [ 5 13]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [5]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [2, 4, 6],
    [1, 4, 5],
    [2, 3, 4],
    [5, 6, 1],
    [3, 4, 5],
    [2, 6, 6]
])
B = np.array([
    [1, 2],
    [3, 4]
])
C = np.array(np.meshgrid(B[0], B[1])).T.reshape(-1, 2)
D = A[np.array([any(np.isin(c_row, a_row).sum() == 2 for c_row in C) for a_row in A])]

print("Возможные пар значений из строк В:\n", C)
print("\nПодходящие строки из A:\n", D)

Возможные пар значений из строк В:
 [[1 3]
 [1 4]
 [2 3]
 [2 4]]

Подходящие строки из A:
 [[1 2 3]
 [2 4 6]
 [1 4 5]
 [2 3 4]]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [6]:
A = np.array([
    [1, 1, 1],
    [2, 2, 3],
    [4, 5, 6],
    [7, 7, 7],
    [8, 9, 8],
    [0, 0, 0],
    [1, 2, 1],
    [3, 3, 3],
    [5, 6, 5],
    [10, 10, 9]
])
find = np.apply_along_axis(lambda row: len(np.unique(row)) > 1, axis=1, arr=A)
B = A[find]
print(B)

[[ 2  2  3]
 [ 4  5  6]
 [ 8  9  8]
 [ 1  2  1]
 [ 5  6  5]
 [10 10  9]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [7]:
unique_rows = np.unique(arr, axis=0)
print(unique_rows)

[[1 3 5]
 [2 4 6]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [11]:
matrix = ([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
diag_len = min(len(matrix), len(matrix[0]))
mult = 1
for i in range(diag_len):
    value = matrix[i][i]
    if value != 0:
        mult *= value
        
print (mult)        

3


In [15]:
matrix = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
diagonal = np.diagonal(matrix[:min(matrix.shape), :min(matrix.shape)])
non_zero = diagonal[diagonal != 0]
print (np.prod(non_zero))

3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [33]:
MX = np.array([1, 2, 2, 4])
MY = np.array([4, 2, 1, 2])
values, counts = np.unique(MX, return_counts=True)
values1, counts1 =np.unique(MY, return_counts=True)
if np.array_equal(values, values1) and np.array_equal(counts, counts1):
    print ("True")
else: 
    print ("False")

True


In [38]:
MX =  ([1, 2, 2, 4])
MY =  ([4, 2, 1, 2])
y_copy = MY[:]

# Проходим по каждому элементу из первого списка
for elem in MX:
    for i in range(len(y_copy)):
        if y_copy[i] == elem:
            y_copy[i] = True
            break
    else:
        print("False")
        break
else:
    if all(item == True for item in y_copy):
        print("True")
    else:
        print("False")       

True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [40]:
Matrix_X = ([6, 2, 0, 3, 0, 0, 5, 7, 0])
candidates = []
for i in range(1, len(Matrix_X)):
    if Matrix_X[i - 1] == 0:
        candidates.append(Matrix_X[i])
find= max(candidates)
find

5

In [44]:
Matrix_X = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
zero_indices = np.where(Matrix_X[:-1] == 0)[0]
f=np.max(Matrix_X[zero_indices + 1])
print(f)

np.int64(5)

* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [48]:
new_x = np.array([2, 2, 2, 3, 3, 3, 5]) 
values = []
counts = []
current = new_x[0]
count = 1
for i in range(1, len(new_x)):
    if new_x[i] == current:
        count += 1
    else:
        values.append(current)
        counts.append(count)
        current = new_x[i]
        count = 1
values.append(current)
counts.append(count)
values = np.array(values)
counts = np.array(counts)

print((values, counts))

([np.int64(2), np.int64(3), np.int64(5)], [3, 3, 1])


In [51]:
x = np.array([2, 2, 2, 3, 3, 3, 5, 8 , 8 , 5 ,1])
ind = np.where(np.diff(x) != 0)[0] + 1
blocks = np.concatenate(([0], ind, [len(x)]))
values = x[blocks[:-1]]
counts = np.diff(blocks)
print((values, counts))

(array([2, 3, 5, 8, 5, 1]), array([3, 3, 1, 2, 1, 1]))


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [65]:
import time
from scipy.spatial.distance import cdist
# Примерные данные
X = np.random.rand(1000, 50)
Y = np.random.rand(1000, 50)



In [68]:
start = time.time()
# ||x - y||^2 = ||x||^2 + ||y||^2 - 2x·y
X_norm = np.sum(X**2, axis=1).reshape(-1, 1)
Y_norm = np.sum(Y**2, axis=1).reshape(1, -1)
D_manual = np.sqrt(X_norm + Y_norm - 2 * np.dot(X, Y.T))
end = time.time()
print("Ручной способ:", end - start, "секунд")

Ручной способ: 0.018216609954833984 секунд


In [69]:
start = time.time()
D_scipy = cdist(X, Y, metric='euclidean')
end = time.time()
print("scipy.cdist:", end - start, "секунд")

scipy.cdist: 0.02966761589050293 секунд


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [16]:
import numpy as np


1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [17]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [18]:
average_calories=round(np.mean(calorie_stats) , 1)
print(average_calories)

106.9


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [19]:
values, counts = np.unique(calorie_stats, return_counts=True)
calorie_stats_sorted = np.column_stack((values, counts ))
calorie_stats_sorted

array([[ 50.,   3.],
       [ 70.,   2.],
       [ 80.,   1.],
       [ 90.,   7.],
       [100.,  17.],
       [110.,  29.],
       [120.,  10.],
       [130.,   2.],
       [140.,   3.],
       [150.,   2.],
       [160.,   1.]])

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [20]:
median_calories=np.median(calorie_stats)
print(median_calories)

110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [21]:
for p in range(1, 101):
    value = np.percentile(calorie_stats, p)
    if value > 60:
        nth_percentile = p
        break
print(f'Наименьший процентиль {nth_percentile}%' )

Наименьший процентиль 4%


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [22]:
more_calories = round(np.mean(calorie_stats > 60) * 100 ,1)
print(more_calories)

96.1


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [23]:
calorie_std = round(np.std(calorie_stats), 1)
print(calorie_std)

19.4


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [24]:
print(
    f"CrunchieMunchies содержит 60 калорий на порцию, в то время как большинство конкурентов {more_calories:.1f}% "
    f"превышают этот показатель.\n"
    f"В среднем калорийность порции хлопьев у конкурентов составляет {average_calories} ± {calorie_std:.2f} калорий на порцию."
)

CrunchieMunchies содержит 60 калорий на порцию, в то время как большинство конкурентов 96.1% превышают этот показатель.
В среднем калорийность порции хлопьев у конкурентов составляет 106.9 ± 19.40 калорий на порцию.
